name: Jekyll Build and Publish to Github Pages
on:
  push:
    branches:
      - master
      - new

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Jekyll Build and Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: elindsey/jekyll-action@master
